hmcts/civil-general-apps-ccd-definition

build.gradle
=> Fixing Jacoco Reports in Gradle

charts/civil-general-apps-ccd-definition/Chart.yaml
=> Update Helm Chart

build.gradle
=> Changing spring boot version to 2.5.6

build.gradle
=> Updating Log4J Dependency

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ccd-definition/CaseEvent/Camunda/CaseEvents.json, ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
https://tools.hmcts.net/jira/browse/CIV-803
1. create new caseEvent LINK_GENERAL_APPLICATION_CASE_TO_PARENT_CASE
2. add permission
```
[ ] Yes
[X] No
```
=> LinkGeneralApplicationCaseToParentCase Event

ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json, ccd-definition/ComplexTypes/1_UnavailableDatesGAspec.json, ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
https://tools.hmcts.net/jira/browse/CIV-727
Hearing screen changes.
```
[ ] Yes
[X] No
```
=> CIV-727 Hearing screen model changes to accept unavailability date range

ccd-definition/CaseField/CaseFieldGAspec.json, ccd-definition/ComplexTypes/GAStatementOfTruthGAspec.json
https://tools.hmcts.net/jira/browse/CIV-709
Screen shot is attached in comment's section.
Fields Validation for Request Order Without Consent Screen - Applicant Journey
```
[ ] Yes
[x] No
```
=> CIV-709 Without Consent Screen Fields validation

ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ccd-definition/CaseEventToComplexTypes/InitiateApplicationGAspec.json, ccd-definition/ComplexTypes/1_UnavailableDatesGAspec.json, ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
https://tools.hmcts.net/jira/browse/CIV-727
https://tools.hmcts.net/jira/browse/CIV-728
Recovering lost changes
```
[ ] Yes
[ ] No
```
=> CIV-727 recover Hearing details screen changes

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ccd-definition/CaseEvent/Camunda/CaseEvents.json, ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
=> work in progress linkGeneralApplication

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ccd-definition/CaseEvent/User/UserEventsGAspec.json, ccd-definition/CaseEventToFields/ApplicationResponseGAspec.json, ccd-definition/CaseField/CaseFieldGAspec.json, ccd-definition/ComplexTypes/GARespondentRepresentativeGAspec.json
=> Respond to Application

build.gradle, ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ccd-definition/CaseEvent/User/UserEventsGAspec.json, ccd-definition/CaseEventToComplexTypes/ApplicationResponseGAspec.json, ccd-definition/CaseField/CaseFieldGAspec.json, ccd-definition/ComplexTypes/GAHearingDetailsRespGAspec.json, charts/civil-general-apps-ccd-definition/values.aat.template.yaml, config/owasp/suppressions.xml, package.json, yarn.lock
=> Response Hearing details

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ccd-definition/CaseEvent/User/UserEventsGAspec.json, ccd-definition/CaseEventToFields/ApplicationResponseGAspec.json
https://tools.hmcts.net/jira/browse/CIV-79
```
[ ] Yes
[ ] No
```
=> Application response

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec.json, ccd-definition/CaseEvent/Camunda/BusinessProcessEvents.json, ccd-definition/CaseEvent/User/UserEventsGAspec.json, ccd-definition/State.json, ccd-definition/UserProfile.json
https://tools.hmcts.net/jira/browse/CIV-778
Move the END_BUSINESS_PROCESS_GASPEC from Civil CCD Def to GA CCD Def. Create the new states in GA CCD Def. Also, when General Application gets created, put it in PENDING_APPLICATION_ISSUED.
```
[ ] Yes
[X] No
```
=> Feature/civ-778_2 END_BUSINESS_PROCESS_GASPEC

ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ccd-definition/CaseField/CaseFieldGAspec.json, ccd-definition/CaseTypeTab/ApplicationDetailsGAspec.json, ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json, ccd-definition/ComplexTypes/GARespondentAgreementGAspec.json, ccd-definition/ComplexTypes/GATypeGAspec.json, ccd-definition/ComplexTypes/GAUrgencyRecordGAspec.json, ccd-definition/ComplexTypes/GAWithOrWithoutNoticeGAspec.json
https://tools.hmcts.net/jira/browse/CIV-949
1. Set up permission
2. Clean general application tab 
```
[ ] Yes
[X] No
```
=> application summary tab

ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec.json, ccd-definition/AuthorisationCaseType/AuthorisationCaseTypeGAspec.json, ccd-definition/CaseEvent/User/UserEventsGAspec.json, ccd-definition/CaseEventToFields/JudicialDecisionGAspec.json, ccd-definition/CaseField/CaseFieldGAspec.json, ccd-definition/CaseRoles.json, ccd-definition/ComplexTypes/GAJudicialDecisionGAspec.json, ccd-definition/FixedLists/GAJudgeDecisionOptionGAspec.json, ccd-definition/UserProfile.json
https://tools.hmcts.net/jira/browse/CIV-80
Judge's screen
```
[ ] Yes
[X] No
```
=> CIV-80 Judge screen - judicial decision

build.gradle
Reverts hmcts/civil-general-apps-ccd-definition#83
=> Revert "Bump org.owasp.dependencycheck from 6.5.3 to 7.0.0"

Jenkinsfile_CNP, bin/build-release-ccd-definition.sh, bin/create-github-release.sh, bin/variables/load-aat-environment-variables.sh, bin/variables/load-demo-environment-variables.sh, bin/variables/load-prod-environment-variables.sh, bin/variables/load-staging-environment-variables.sh, bin/wait-for.sh, build.gradle
setting url values
```
[ ] Yes
[ ] No
```
=> aat environment fixes

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json, ga-ccd-definition/CaseEventToFields/JudicialDecisionGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GAJudicialRequestMoreInfoGAspec.json, ga-ccd-definition/FixedLists/GAJudgeRequestMoreInfoOptionGAspec.json
https://tools.hmcts.net/jira/browse/CIV-82
CIV-82 Judge's journey : Request more information screen
```
[ ] Yes
[X] No
```
=> CIV-82 Judge's journey : Request more information screen

Jenkinsfile_CNP, bin/variables/load-staging-environment-variables.sh, charts/civil-general-apps-ccd-definition/values.aat.template.yaml, charts/civil-general-apps-ccd-definition/values.preview.template.yaml
=> changes for aat environment fixes

Jenkinsfile_CNP, bin/variables/load-staging-environment-variables.sh, charts/civil-general-apps-ccd-definition/values.aat.template.yaml
=> adding civil service pod to aat

ga-ccd-definition/ComplexTypes/GAJudgesHearingListGAspec.json, ga-ccd-definition/ComplexTypes/GAJudicialMakeAnOrderGAspec.json, ga-ccd-definition/ComplexTypes/GAJudicialRequestMoreInfoGAspec.json
https://tools.hmcts.net/jira/browse/CIV-1819
Text Changes for Judges Screens
```
[ ] Yes
[X] No
```
=> Text Changes for Judges Screens

e2e/fixtures/events/createClaim.js, e2e/pages/generalApplication/applicationDetails.page.js, e2e/pages/generalApplication/judgesJourneyPages/drawGeneralOrder.page.js, e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js, e2e/pages/generalApplication/judgesJourneyPages/writtenRepresentations.page.js
https://tools.hmcts.net/jira/browse/CIV-1866
https://tools.hmcts.net/jira/browse/CIV-1818
https://tools.hmcts.net/jira/browse/CIV-1819
=> E2E Automation tests - Judges journey updates

Jenkinsfile_CNP, e2e/fixtures/events/createClaim.js, e2e/pages/generalApplication/applicationDetails.page.js, e2e/pages/generalApplication/judgesJourneyPages/drawGeneralOrder.page.js, e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js, e2e/pages/generalApplication/judgesJourneyPages/writtenRepresentations.page.js, ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json, ga-ccd-definition/ComplexTypes/GAHearingDetailsRespGAspec.json, ga-ccd-definition/ComplexTypes/GAJudgesHearingListGAspec.json
=> Sprint5integration

build.gradle, charts/civil-general-apps-ccd-definition/Chart.yaml, charts/civil-general-apps-ccd-definition/values.yaml
commenting out functional and smoke test temporarily
```
[ ] Yes
[ ] No
```
=> temporary changes to update charts

e2e/api/testingSupport.js, e2e/pages/caseView.page.js, e2e/pages/generalApplication/applicantSummary.page.js, e2e/pages/generalApplication/judgesJourneyPages/drawGeneralOrder.page.js, e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js, e2e/pages/generalApplication/judgesJourneyPages/requestMoreInformation.page.js, e2e/pages/generalApplication/responseJourneyPages/responseConfirmation.page.js, e2e/pages/generalApplication/responseJourneyPages/responseSummary.page.js, e2e/steps_file.js, e2e/tests/1v1GeneralApplication_test.js, e2e/tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/smoke_test.js
=>  CIV-1865: Enabled Response and Judges journey 

e2e/pages/generalApplication/generalApplicationTypes.js, e2e/pages/generalApplication/judgesJourneyPages/listForHearing.page.js, e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js, e2e/steps_file.js, e2e/tests/1v1GeneralApplication_test.js, e2e/tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/multiparty-ga-tests/2v1GeneralApplication_test.js, ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ga-ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseEvent/Camunda/ChangeStateToAwaitingJudicialDecisionGAspec.json, ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json, ga-ccd-definition/CaseEventToFields/JudicialDecisionGAspec.json, ga-ccd-definition/ComplexTypes/GAJudgesHearingListGAspec.json, ga-ccd-definition/ComplexTypes/GAJudicialMakeAnOrderGAspec.json, ga-ccd-definition/FixedLists/GAJudgeOrderClaimantOrDefenseFixedList.json
=> Sprint6integration

charts/civil-general-apps-ccd-definition/values.aat.template.yaml, charts/civil-general-apps-ccd-definition/values.preview.template.yaml
=> updated image policy

e2e/pages/generalApplication/responseJourneyPages/responseConfirmation.page.js, e2e/steps_file.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, ga-ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GAResondentResponseGAspec.json
https://tools.hmcts.net/jira/browse/CIV-2002
Make changes to civil-general-applications and civil-general-app-ccd-definition for respondent details
```
[ ] Yes
[X] No
```
=> respondent validation

charts/civil-general-apps-ccd-definition/values.aat.template.yaml, charts/civil-general-apps-ccd-definition/values.preview.template.yaml
=> added app instrumentation key logic to be picked up from vault

e2e/tests/ui_tests/1v1GeneralApplication_test.js, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/AuthorisationCaseField/StaffGAspec.json, ga-ccd-definition/AuthorisationCaseField/caseAccessAssignmentGAspec.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json
https://tools.hmcts.net/jira/browse/CIV-934
A Without Notice application should be hidden from any Legal Reps other than the Applicant
```
[x] Yes
[ ] No
```
=> CIV-934 Add Respondent Sol GA Details Collection

e2e/api/apiRequest.js, e2e/api/steps.js, e2e/api/testingSupport.js, e2e/fixtures/ga-ccd/judgeMakeDecision.js, e2e/tests/api_tests/api_1v1_directions_order_test.js, e2e/tests/api_tests/api_1v1_judge_decision_addln_info_test.js, e2e/tests/api_tests/api_1v1_test.js, e2e/tests/api_tests/api_1v1_written_rep_test.js
https://tools.hmcts.net/jira/browse/CIV-2405
Scenario 1:
PreConditionState:  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION
PostConditionState: AWAITING_WRITTEN_REPRESENTATIONS
Scenario 2:
PreConditionState:  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION
PostConditionState: AWAITING_DIRECTIONS_ORDER_DOCS
Scenario 3:
PreConditionState:  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION
PostConditionState: AWAITING_ADDITIONAL_INFORMATION
```
[ ] Yes
[ ] No
```
=> Judge make decision - Awaiting Addln Info

config/owasp/suppressions.xml
=> supressions update

e2e/api/steps.js, e2e/pages/caseView.page.js, e2e/pages/generalApplication/gaConfirmation.page.js, e2e/pages/generalApplication/hearingDetails.page.js, e2e/pages/generalApplication/judgesJourneyPages/judgesConfirmation.page.js, e2e/pages/generalApplication/responseJourneyPages/responseConfirmation.page.js, e2e/pages/generalApplication/responseJourneyPages/responseHearingDetails.page.js, e2e/pages/generalApplication/responseJourneyPages/responseSummary.page.js, e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/ui_tests/smoke_test.js
https://tools.hmcts.net/jira/browse/CIV-2618
=> CIV-2618 - Wait for business process to finish e2e code refactor

e2e/pages/generalApplication/judgesJourneyPages/judgesSummary.page.js, e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/ui_tests/smoke_test.js, ga-ccd-definition/CaseEventToFields/JudicialDecisionGAspec.json, ga-ccd-definition/CaseTypeTab/ApplicationDetailsGAspec.json
https://tools.hmcts.net/jira/browse/CIV-2235
To display the extra information on Judges Summary screen for these 3 journeys.
written representation, 
directions order and 
additional information
```
[ ] Yes
[x] No
```
=> Display Judge decision in application's summary page

charts/civil-general-apps-ccd-definition/values.preview.template.yaml, e2e/pages/generalApplication/judgesJourneyPages/applicationDocument.page.js, ga-ccd-definition/CaseEvent/Camunda/DocmosisEvents.json
temp pointing to pr 305 of GA
```
[ ] Yes
[ ] No
```
=> switching on docmosis callback

e2e/pages/generalApplication/judgesJourneyPages/applicationDocument.page.js, e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/ui_tests/smoke_test.js
https://tools.hmcts.net/jira/browse/CIV-2603
=> WIP: CIV-1585 pdf automation

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-1950
Suppress Vulnerability
```
[ ] Yes
[ ] No
```
=> Suppress Vulnerability

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ga-ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec.json, ga-ccd-definition/CaseEvent/Camunda/ChangeStateToAwaitingResponseTimeExpiredGAspec.json
https://tools.hmcts.net/jira/browse/CIV-2682
Update state of timer expired state for Written Representations, Directions Order and Additional Info to Additional Response Time Expired instead of Application Submitted - Awaiting Judicial Decision
```
[ ] Yes
[ ] No
```
=> CIV-2682 Change app state to Response time expired

e2e/pages/generalApplication/judgesJourneyPages/listForHearing.page.js
https://tools.hmcts.net/jira/browse/CIV-1636
=> Judges Hearing Screen labels assertion added

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/AuthorisationCaseField/StaffGAspec.json, ga-ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
https://tools.hmcts.net/jira/browse/CIV-2715
respondentSolicitor1EmailAddress" is empty in General Applications case Data
```
[ ] Yes
[x] No
```
=> Removed variable respondentSolicitor1EmailAddress

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseEventToFields/InitiateApplicationGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
https://tools.hmcts.net/jira/browse/CIV-2833
Refactor use of string on general app notification deadline
```
[ ] Yes
[x] No
```
=> CIV-2463 Refactor use of string on general app notification deadline

charts/civil-general-apps-ccd-definition/values.aat.template.yaml, charts/civil-general-apps-ccd-definition/values.preview.template.yaml
=> added jrd url for civil service

ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json, ga-ccd-definition/ComplexTypes/GAJudgesHearingListGAspec.json
US : https://tools.hmcts.net/jira/browse/CIV-2797
Sub-task : https://tools.hmcts.net/jira/browse/CIV-3063
Add label **Where do you want to list for a hearing?**  in GAJudicialHearingDetailsScreen
```
[ ] Yes
[X] No
```
=> Added new label

.gitignore, Jenkinsfile_CNP, charts/civil-general-apps-ccd-definition/Chart.yaml, codecept.conf.js, config/owasp/suppressions.xml, e2e/config.js, package.json
=> update test result folder structure

charts/civil-general-apps-ccd-definition/values.aat.template.yaml, charts/civil-general-apps-ccd-definition/values.preview.template.yaml, e2e/pages/generalAppCommons.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/smoke_test.js, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/CaseTypeTab/ServiceRequestGAspec.json, package.json
=> switching on tests and updated xui image

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ga-ccd-definition/CaseEvent/Camunda/ChangeStateToAwaitingJudicialDecisionGAspec.json, ga-ccd-definition/CaseEvent/Camunda/ChangeStateToAwaitingResponseTimeExpiredGAspec.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec.json
https://tools.hmcts.net/jira/browse/CIV-3627
Add publish Y to all relevant events as per DMNS
```
[ ] Yes
[ ] No
```
=> CIV-3627 Add Publish field to publish data in WA Queue

ga-ccd-definition/CaseEvent/User/UserEventsGAspec.json
CIV-3374 Update preConditionState in Make decision event.
https://tools.hmcts.net/jira/browse/CIV-3374
Update pre conditions state for event make decision.
```
[ ] Yes
[X] No
```
=> CIV-3374 Update preConditionState in Make decision event.

e2e/tests/api_unspec_claim_tests/api_1v1_judge_list_for_hearing_test.js, e2e/tests/api_unspec_claim_tests/api_1v2_additional_info_test.js, e2e/tests/api_unspec_claim_tests/api_1v2_application_dissmised_test.js, e2e/tests/api_unspec_claim_tests/api_1v2_awaiting_written_representation_test.js, e2e/tests/api_unspec_claim_tests/api_1v2_directions_order_test.js
=> removing api test tag

bin/variables/load-staging-environment-variables.sh, charts/civil-general-apps-ccd-definition/values.aat.template.yaml
=> CIV-4462 Fix master

bin/add-roles.sh, charts/civil-ga-ccd/values.preview.template.yaml, config/owasp/suppressions.xml, e2e/api/steps.js, e2e/config.js, e2e/fixtures/ga-ccd/judgeMakeDecision.js, e2e/tests/api_unspec_claim_tests/api_1v1_judge_decision_uncloak_application_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec.json, ga-ccd-definition/AuthorisationCaseType/AuthorisationCaseTypeGAspec.json, ga-ccd-definition/AuthorisationComplexType/judgeProfileGAspec.json, ga-ccd-definition/AuthorisationComplexType/solicitorGAspec.json, ga-ccd-definition/AuthorisationComplexType/staff.json, ga-ccd-definition/CaseEvent/Camunda/CaseEvents.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json, ga-ccd-definition/State.json
=> Sprint3integration

charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml
=> updated postgres charts

Jenkinsfile_CNP, bin/add-roles.sh, charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.preview.template.yaml, e2e/fixtures/events/createClaim.js
- updated create claim
- modified jenkincnp to udate exclusions
```
[ ] Yes
[ ] No
```
=> pipeline fix

bin/add-roles.sh, config/owasp/suppressions.xml
=> Supressed vulnerability temporarly

e2e/tests/api_unspec_claim_tests/api_1v1_judge_decision_uncloak_application_test.js
https://tools.hmcts.net/jira/browse/CIV-5085
add api test case for https://tools.hmcts.net/jira/browse/CIV-5085
```
[ ] Yes
[x] No
```
=> CIV-5085 add api test case for update ga status with visible to resp sol

e2e/tests/api_unspec_claim_tests/api_1v1_judge_decision_uncloak_application_test.js
Reverts hmcts/civil-general-apps-ccd-definition#350
=> Revert "CIV-5085 add api test case for update ga status with visible to resp sol"

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
https://tools.hmcts.net/jira/browse/CIV-5243
Remove Caseworker civil admin user role
```
[ ] Yes
[ ] No
```
=> CIV-5243 Remove Caseworker civil admin

bin/add-roles.sh, e2e/pages/caseView.page.js, ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec.json, ga-ccd-definition/AuthorisationCaseType/AuthorisationCaseTypeGAspec.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-5331
created a new role ga-basic-access in demo and given Read permission to all the caseevents, case states, case fields and also assigned this access profile to specified and challenged roles and also to hmcts judiciary
```
[x ] Yes
[ ] No
```
=> Civ 5331 Adding additional access profile for challenge and specific access

Jenkinsfile_nightly
Reverts hmcts/civil-general-apps-ccd-definition#389
=> Revert "Enabling full functional tests in nightly build"

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
https://tools.hmcts.net/jira/browse/CIV-5561
Hide service request tab for judge user role
```
[ ] Yes
[ ] No
```
=> CIV-5561 Hide service request tab for judge

charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml, e2e/pages/caseView.page.js, e2e/tests/ui_tests/smoke_test.js
=> update on the keys

ga-ccd-definition/ComplexTypes/GAWithOrWithoutNoticeGAspec.json
https://tools.hmcts.net/jira/browse/CIV-6346
Fix label for the field "isWithNotice"
```
[ ] Yes
[ ] No
```
=> CIV-6346 Fix typo

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml
=> updated helm charts

e2e/fixtures/ga-ccd/judgeMakeDecision.js
https://tools.hmcts.net/jira/browse/CIV-6284
Set value for mandatory field to prevent null pointer
```
[ ] Yes
[ ] No
```
=> CIV-6284 Fix api test

Jenkinsfile_nightly, config/owasp/suppressions.xml, e2e/pages/caseView.page.js, e2e/steps_file.js, e2e/steps_file_WA.js, e2e/tests/api_wa_tests/1v1_unspec_ga_wa_specific_access_test.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/ui_tests/wa_tests/1v1_Unspec_GA_WA_scheduleHearing_test.js, e2e/tests/ui_tests/wa_tests/1v2_Spec_GA_WA_reviewAppOrder_test.js
- [ x] tests have been updated / new tests has been added (if needed)
Bug was identified that continue button found while running specific access wa ui test.  Added a wait befor continue button which fixed this issue.
```
[x ] Yes
[ ] No
```
=> continue button not found bug fix - specific-access-wa-ui-test

e2e/pages/generalApplication/judgesJourneyPages/drawGeneralOrder.page.js, e2e/steps_file.js, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
https://tools.hmcts.net/jira/browse/CIV-6688
Add permission to hearing "Draw a general order" label field.
```
[ ] Yes
[x] No
```
=> CIV-6688 Add permission to hearing order heading

ga-ccd-definition/ComplexTypes/GAMakeAppVisibleToAll.json
https://tools.hmcts.net/jira/browse/CIV-6672
update the wording on the Uncloak checkbox to "Do you wish to make the application visible to all parties?"
```
[ ] Yes
[ ] No
```
=> CIV-6672 Change ElementLabel wording

e2e/pages/generalApplication/applicantSummary.page.js, e2e/pages/generalApplication/judgesJourneyPages/judgesSummary.page.js, e2e/pages/generalApplication/responseJourneyPages/responseSummary.page.js, e2e/steps_file_WA.js, ga-ccd-definition/CaseTypeTab/ApplicationDetailsGAspec.json
https://tools.hmcts.net/jira/browse/CIV-6669
Change Application "Summary" tab name to "Application"
```
[ ] Yes
[ ] No
```
=> CIV-6669 Rename tab name

e2e/pages/generalApplication/judgesJourneyPages/listForHearing.page.js
https://tools.hmcts.net/jira/browse/CIV-6682
Refactor hearing screen applicant and respondent preference text
```
[ ] Yes
[ ] No
```
=> CIV-6682 Refactor hearing screen appln and resp preference wording

ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-6064
Added missing role to access profile specific-access-ctsc
```
[ ] Yes
[x ] No
```
=> Added specific-access-ctsc role

e2e/pages/generalAppCommons.js
https://tools.hmcts.net/jira/browse/CIV-6813
Fix local judge credentials
```
[ ] Yes
[ ] No
```
=> CIV-6813 Fix local judge credentials

e2e/pages/generalApplication/responseJourneyPages/responseSummary.page.js
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-6927
Corrected tab name which is causing nightly failure 
```
[ ] Yes
[x ] No
```
=> CIV-6927 corrected tab name in responsesummary - nightly failure fixed

ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-6196
Bug identified during testing for after SDO scenario and Before SDO scenario for ScheduleApplicationHearing task
```
[ ] Yes
[x ] No
```
=> CIV-6196 bug Schedule Application Hearing task is not visible to nbc admin

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml
=> CCD latest version autoscale issue fix

e2e/pages/generalApplication/applicantSummary.page.js, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GAHearingDateGAspec.json
https://tools.hmcts.net/jira/browse/CIV-7026
Fix N245 Label issue
```
[ ] Yes
[ ] No
```
=> CIV-7026 Fix N245 Label issue

.github/dependabot.yml, .github/renovate.json
https://tools.hmcts.net/jira/browse/CIV-7084
Dependabot removed and its tasks delegated to renovate
```
[ ] Yes
[x] No
```
=> CIV-7084 remove dependabot and delegate its tasks to renovate

Jenkinsfile_CNP, bin/variables/load-preview-environment-variables.sh, bin/variables/load-staging-environment-variables.sh, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml
=> CIV-7118 relevant commits with the changes required

e2e/pages/generalApplication/gaConfirmation.page.js, e2e/steps_file.js
https://tools.hmcts.net/jira/browse/CIV-7180
Added tests for ui confirmation message
```
[ ] Yes
[x ] No
```
=> CIV-7014 confirmation message on tests

e2e/api/steps.js, e2e/api/testingSupport.js, e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/ui_tests/wa_tests/1v1_Unspec_GA_WA_scheduleHearing_test.js, e2e/tests/ui_tests/wa_tests/1v2_Spec_GA_WA_reviewAppOrder_test.js
https://tools.hmcts.net/jira/browse/CIV-7495
```
[ ] Yes
[ ] No
```
=> CIV-7495 awaiting business process

Jenkinsfile_CNP, e2e/tests/api_spec_claim_test/api_spec_1v2_afterSDO_GeneralApplication_test.js
=> CIV-0000 Update api_spec_1v2_afterSDO_GeneralApplication_test.js

e2e/pages/generalApplication/gaConfirmation.page.js, e2e/pages/generalApplication/gaPBANumber.page.js, e2e/steps_file.js
https://tools.hmcts.net/jira/browse/CIV-7329
=> CIV-7329 UI automation changes for Vary Judgement and Vary Order fee

e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js
=> CIV-0000 nightly build fix

charts/civil-ga-ccd/values.template.yaml
https://tools.hmcts.net/jira/browse/CIV-7412
Changed xui image from "pr-2780" to latest
```
[ ] Yes
[ ] No
```
=> CIV-7412 Reverted xui image to latest

e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplicationR2_test.js
https://tools.hmcts.net/jira/browse/CIV-7322
=> CIV-7322 UI test changes

e2e/config.js, e2e/fixtures/events/claim/claimantResponseSpec.js, e2e/fixtures/events/claim/claimantResponseSpec2v1.js, e2e/fixtures/events/claim/defendantResponseSpec.js, e2e/fixtures/events/claim/defendantResponseSpec1v2.js, e2e/fixtures/events/claim/defendantResponseSpec2v1.js, e2e/fixtures/events/claimantResponseSpec.js, e2e/fixtures/events/claimantResponseSpec2v1.js, e2e/fixtures/events/createClaimSpec.js, e2e/fixtures/events/defendantResponseSpec.js, e2e/fixtures/events/defendantResponseSpec1v2.js, e2e/fixtures/events/defendantResponseSpec2v1.js, e2e/tests/api_spec_claim_test/api_spec_1v2_afterSDO_GeneralApplication_test.js
=> CIV-7588 relevant changes required to modify court location names

e2e/config.js, e2e/fixtures/ga-ccd/state.js, e2e/tests/ui_tests/1v1GeneralApplicationR2_test.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/1v1_CP_HearingNotice_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js, e2e/tests/ui_tests/wa_tests/1v1_Unspec_GA_WA_scheduleHearing_test.js, e2e/tests/ui_tests/wa_tests/1v2_Spec_GA_WA_reviewAppOrder_test.js
https://tools.hmcts.net/jira/browse/CIV-7182
=> CIV-7182 Refactor GA UI tests 

e2e/api/steps.js
=> CIV-0000 corrections to pass in pbav3 variable

codecept.conf.js, e2e/api/steps.js, e2e/fixtures/events/createClaim.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js, package.json, sonar-project.properties
=> CIV-0000 nightly test fix and switching on bail true for nightly

package.json
=> CIV-0000 change puppeteer version

e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js
=> CIV-0000 Skip test temporarly

e2e/api/steps.js, e2e/tests/api_spec_claim_test/api_spec_1v2_claimant_response_offline_nightly_test.js, e2e/tests/api_spec_claim_test/api_spec_1v2_defendant_response_offline_nightly_test.js
https://tools.hmcts.net/jira/browse/CIV-7778
fix defendantResponseSpecClaim affected by ga doc
```
[ ] Yes
[x] No
```
=> CIV-7778 fix defendantResponseSpecClaim affected by ga doc

e2e/api/steps.js, e2e/fixtures/ga-ccd/createGeneralApplication.js, e2e/tests/api_spec_claim_test/api_spec_1v1_directions_order_test.js, e2e/tests/api_unspec_claim_tests/api_1v1_directions_order_test.js
https://tools.hmcts.net/jira/browse/CIV-7627
add api test for Urgent Application to Vary Judgment
```
[ ] Yes
[x] No
```
=> CIV-7627 add urgent test

Jenkinsfile_CNP, bin/utils/process-definition.sh, package.json
=> CIV-0000 Update process-definition.sh

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json
https://tools.hmcts.net/jira/browse/CIV-8066
Hide the events Hide Refer to Judge and Refer to Legal Advisor events from Caseworkers, Legal Advisor as they will no longer result in work allocation tasks being created and will lead to confusion for users.
```
[ ] Yes
[ ] No
```
=> CIV-8066 Refactor caseworker and adviser permission

e2e/pages/caseView.page.js, e2e/pages/generalApplication/applicationType.page.js, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GeneralApplicationGAspec.json, ga-ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-8142
Spell mistake corrected; removed e from Judgement
```
[ ] Yes
[x ] No
```
=> CIV-8142 Removed e from Summary Judgment wording

package.json
=> CIV-0000 adding new tasks for yarn and adding puppeteer core to fix version

e2e/pages/generalApplication/caseFile.page.js, e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_ApplicationOrders_test.js
https://tools.hmcts.net/jira/browse/CIV-7431
=> CIV-7431 UI Automation

e2e/steps_file.js, e2e/tests/ui_tests/1v1_CP_ApplicationOrders_test.js
=> CIV-0000 signin approach changes

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.enableWA.preview.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml
=> CIV-0000 wa chart changes

e2e/api/steps.js
=> CIV-0000 remove main claim pbav3 assertions

charts/civil-ga-ccd/values.template.yaml
=> CIV-0000 change xui to latest

Jenkinsfile_CNP
=> CIV-0000 changes required with the new exclusions

e2e/api/steps.js, e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js
https://tools.hmcts.net/jira/browse/CIV-5226
ga fees
```
[ ] Yes
[x] No
```
=> CIV-5226 ga fees mixed types api test

e2e/api/steps.js, e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js
https://tools.hmcts.net/jira/browse/CIV-8533
Added the api test for uncloaking the consent order. 
```
[ ] Yes
[ ] No
```
=> CIV-8533 Added API consent order uncloak

e2e/api/steps.js, e2e/fixtures/ga-ccd/judgeMakeDecision.js, e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js, e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js, e2e/tests/api_unspec_claim_tests/api_1v1_judge_decision_uncloak_application_test.js, e2e/tests/api_unspec_claim_tests/api_1v2_defendant_response_offline_nightly_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js
https://tools.hmcts.net/jira/browse/CIV-8531
notify api test
```
[ ] Yes
[x] No
```
=> CIV-8531 api notify

.github/renovate.json
=> CIV-0000 Add schedule back

e2e/pages/generalAppCommons.js, e2e/pages/generalApplication/applicantSummary.page.js, e2e/steps_file.js, e2e/tests/ui_tests/1v1GeneralApplicationR2_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
=> CIV-8933 introducing payment access permissions

e2e/api/steps.js, e2e/tests/api_unspec_claim_tests/api_1v1_adjourn_vacate_ga_test.js
https://tools.hmcts.net/jira/browse/CIV-7575
Adjourn or Vacate Hearing Fee Scenarios
```
[ ] Yes
[x] No
```
=> CIV-7575 api test

e2e/api/steps.js
https://tools.hmcts.net/jira/browse/CIV-8310
remove ga draft fields from test case data
```
[ ] Yes
[x] No
```
=> CIV-8310 fix nightly test bug caused by new added ga draft fields

bin/import-dmn-diagram.sh, bin/import-wa-bpmn-diagram.sh
=> CIV-0000 changes to script to avoid duplicate upload

e2e/fixtures/ga-ccd/createGeneralApplication.js, e2e/pages/generalApplication/generalApplicationTypes.js, ga-ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json
https://tools.hmcts.net/jira/browse/CIV-8430
Update "Adjourn or Vacate Hearing" to "Adjourn Hearing"
```
[ ] Yes
[ ] No
```
=> CIV-8430 Rename Adjourn or vacate a hearing

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ga-ccd-definition/CaseEvent/Camunda/BusinessProcessEvents.json, ga-ccd-definition/ComplexTypes/BusinessProcessGAspec.json, ga-ccd-definition/FixedLists/BusinessProcessStatusGAspec.json
https://tools.hmcts.net/jira/browse/CIV-8961
- Added new business process updating the status of failed events
- Added new field failedExternalTaskId
- Added new state "Failed"
```
[ ] Yes
[ ] No
```
=> CIV-8961 Polling Event Emitter

e2e/fixtures/ga-ccd/judgeMakeDecision.js, e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js, ga-ccd-definition/FixedLists/MakeAppAvailableCheckGAspec.json
https://tools.hmcts.net/jira/browse/CIV-9298
code clean
```
[ ] Yes
[x] No
```
=> CIV-9298 code clean

charts/civil-ga-ccd/values.template.yaml, e2e/config.js, e2e/pages/caseView.page.js, e2e/pages/generalApplication/caseFile.page.js
=> CIV-9676 master pipeline fixes

charts/civil-ga-ccd/Chart.yaml
=> CIV-0000 civil service chart upgrade

bin/add-roles.sh, src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/CIV-7897
Update Event Roles
```
[ ] Yes
[x] No
```
=> CIV-7897 Update Event Roles

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-5339
added new profile
```
[ ] Yes
[x] No
```
=> CIV-5339 - Release 2 - LIP v LIP Update Access Profile 

charts/civil-ga-ccd/values.enableWA.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/RWA-2607
```
[ ] Yes
[ ] No
```
=> CIV-0000 remove AAT logging from wa-case-event-handler

charts/civil-ga-ccd/values.enableWA.preview.template.yaml
=> CIV-0000 updated servicebus name

e2e/api/steps.js
=> CIV-0000 fix main case respond

.github/workflows/main.yml, e2e/pages/generalApplication/judgesJourneyPages/judgeDecision.page.js, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/FixedLists/GAJudgeDecisionOptionGAspec.json
https://tools.hmcts.net/jira/browse/CIV-10069
Update Judicial landing page to include " Free form order " and existing wording
```
[ ] Yes
[ ] No
```
=> CIV-10069 Refactor Judicial Decision options

Jenkinsfile_CNP, charts/civil-ga-ccd/values.template.yaml, e2e/api/apiRequest.js
=> CIV-10448 S2S refactor 

ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/GeneralApplicationGAspec.json
https://tools.hmcts.net/jira/browse/CIV-10585
Update file types and mb to MB
```
[ ] Yes
[ ] No
```
=> CIV-10585 Update file types and mb to MB

ga-ccd-definition/CaseEventToComplexTypes/FinalOrder/FurtherHearingFinalOrders.json, ga-ccd-definition/ComplexTypes/FinalOrder/AssistedOrderFurtherHearingDatesAvoid.json, ga-ccd-definition/ComplexTypes/FinalOrder/FurtherHearingFinalOrders.json
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-10426
```
[ ] Yes
[x ] No
```
=> CIV-10426 Added new fields for Assisted Order further hearing

e2e/fragments/date.js
Fix Free Form Order 7 Days calculation
```
[ ] Yes
[ ] No
```
=> CIV-9786 Fix FreeForm Order Date

e2e/pages/generalAppCommons.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_ConsentOrders_test.js
https://tools.hmcts.net/jira/browse/CIV-8301
=> CIV-8301 Fix for nightly tests

e2e/api/steps.js, e2e/pages/generalApplication/gaConfirmation.page.js, e2e/steps_file.js
https://tools.hmcts.net/jira/browse/CIV-10646
application text change
```
[ ] Yes
[x] No
```
=> CIV-10646 application text change

e2e/pages/generalApplication/hearingDate.page.js, ga-ccd-definition/ComplexTypes/GAHearingDateGAspec.json, ga-ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json
https://tools.hmcts.net/jira/browse/CIV-10231
1. Update any reference to Settle or Discontinue by consent to Settle by consent including the error messages
2. On the Is there a hearing screen, update the question asked to be: Is the application for an adjournment of a hearing which is at least 14 days away?
and if yes date field reads: Please provide the hearing dates
Help text to be updated to: If there is is more than one hearing, please provide the date of the earliest hearing
```
[ ] Yes
[ ] No
```
=> CIV-10231 Update Application Type Name

e2e/pages/generalAppCommons.js
https://tools.hmcts.net/jira/browse/CIV-10664
Add missing word in judge recital text
```
[ ] Yes
[ ] No
```
=> CIV-10664 Add missing word in recital text

e2e/pages/generalApplication/judgesJourneyPages/drawGeneralOrder.page.js
https://tools.hmcts.net/jira/browse/CIV-10926
Update written rep label
```
[ ] Yes
[ ] No
```
=> CIV-10926 Update written rep label

e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js, e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js
=> CIV-0000 temporary skip of after sdo tests

bin/add-roles.sh, src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/CIV-10823
```
[ ] Yes
[x] No
```
=> CIV-10823 new role added for pcq

bin/build-release-ccd-definition.sh, charts/civil-ga-ccd/values.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml, e2e/config.js
=> CIV-14006 TESTING

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-13537
LR vs Lip with notice
```
[ ] Yes
[x] No
```
=> CIV-13537 LR vs Lip with notice

e2e/fixtures/ga-ccd/createGeneralApplication.js
https://tools.hmcts.net/jira/browse/CIV-14142
```
[ ] Yes
[ ] No
```
=> CIV-14142 Remove Ga Flags from testcase

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/ComplexTypes/GAHelpWithFees-CUI-nonprod.json, ga-ccd-definition/ComplexTypes/GeneralApplicationGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14008
```
[ ] Yes
[ ] No
```
=> CIV-0000 ga_lip_bulk to master

bin/build-release-ccd-definition.sh, ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseField-HWF-R2-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEventToComplexTypes/NoRemission-HWF-CUI-nonprod.json, ga-ccd-definition/CaseEventToFields/NoRemission-HWF-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-HWF-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/ComplexTypes/HelpWithFeesDetails-HWF-CUI-nonprod.json, ga-ccd-definition/ComplexTypes/HelpWithFeesMoreInformation-HWF-CUI-nonprod.json, ga-ccd-definition/FixedLists/ConfirmPaymentMade-HWF-CUI-nonprod.json, ga-ccd-definition/FixedLists/HWFFeeDetailsSummary-HWF-CUI-nonprod.json, ga-ccd-definition/FixedLists/HwfInformationProof-HWF-CUI-nonprod.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-nonprod.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles-prod.json, ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
https://tools.hmcts.net/jira/browse/CIV-12761
CIV-12761 Application Fee - HwF Caseworker - No remission
```
[ ] Yes
[x] No
```
=> CIV-12761 Application Fee - HwF Caseworker - No remission

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseField-HWF-R2-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEventToFields/HelpWithFeesMoreInformation-HWF-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-HWF-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-12771
Application Fee - HwF Caseworker - More Information Required
```
[ ] Yes
[x] No
```
=> CIV-12771 Application Fee - HwF Caseworker

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEventToFields/FullRemission-HWF-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-12773
Application Fee - HwF Caseworker - Full remission HwF - granted
```
[ ] Yes
[x] No
```
=> CIV-12773 Application Fee - HwF Caseworker - Full remission HwF - granted

e2e/api/apiRequest.js, e2e/api/steps.js, e2e/config.js, e2e/fixtures/events/cui/createClaimUnrepresentedClaimant.js, e2e/fixtures/events/cui/createGAUnrepresented.js, e2e/tests/api_spec_claim_test/api_spec_1v1_lip_lip_directions_order_test.js
https://tools.hmcts.net/jira/browse/CIV-14235
api testing for GA
```
[ ] Yes
[x] No
```
=> CIV-14235 api testing for GA

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml
DTSCCI-490
remove deprecated property volume lib
```
[ ] Yes
[ ] No
```
=> DTSCCI-490 remove deprecated property volume lib

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEventToComplexTypes/PartialRemission-HWF-CUI-nonprod.json, ga-ccd-definition/CaseEventToFields/FullRemission-HWF-CUI-nonprod.json, ga-ccd-definition/CaseEventToFields/PartialRemission-HWF-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-12765
Application Fee - HwF Caseworker - Part Remission
```
[ ] Yes
[x] No
```
=> CIV-12765 HwF Caseworker - Part Remission

charts/civil-ga-ccd/Chart.yaml
DTSCCI-567
rollback servicebus chart
```
[ ] Yes
[ ] No
```
=> DTSCCI-567 rollback servicebus chart

e2e/tests/ui_tests/ga_smoke_test.js
- skip test temporarily
```
[ ] Yes
[ ] No
```
=> CIV-000 Skip failing test

ga-ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14228
GA upload additional documents
```
[ ] Yes
[x] No
```
=> CIV-14228 GA upload additional documents

charts/civil-ga-ccd/Chart.yaml
=> CIV-0000 Update servicerbus version

ga-ccd-definition/FixedLists/DocumentType.json
https://tools.hmcts.net/jira/browse/CIV-14127
Court Response Document - Without notice becomes with notice
```
[ ] Yes
[ ] No
```
=> CIV-14127 Court Response Document - Without notice becomes with notice

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/BusinessProcessEvents-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/NotificationEventsGAspec-CUI-nonprod.json
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-12762
CIV-12772
CIV-12766
CIV-12763
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/1049
```
[ ] Yes
[x ] No
```
=> CIV-12772 Application fee - Claimant notification  Caseworker HWF events

charts/civil-ga-ccd/values.preview.template.yaml, e2e/tests/api_unspec_claim_tests/api_1v1_afterSDO_GeneralApplication_test.js, e2e/tests/ui_tests/ga_smoke_test.js
https://tools.hmcts.net/jira/browse/CIV-14845
update tests for Birmingham being part of NRO
```
[ ] Yes
[x ] No
```
=> CIV-14845 Birmingham now part of national rollout

ga-ccd-definition/CaseTypeTab/ApplicationDetailsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseTypeTab/ApplicationDetailsGAspec.json
https://tools.hmcts.net/jira/browse/CIV-14036
Move LIP HWF application Tab details to non-prod file
```
[ ] Yes
[ ] No
```
=> CIV-14036 Add HwF info in nonprod appln tab

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.template.yaml, charts/civil-ga-ccd/values.yaml
=> DTSCCI-613 postgres chart changes for wa

Jenkinsfile_CNP, README.md, charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.enableWA.preview.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml, charts/civil-ga-ccd/values.yaml
=> DTSCCI-613 Revert WA fix

e2e/pages/generalApplication/hearingNoticePages/hearingSchedule.page.js
=> DTSCCI-583 - Updating Basildon Address

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.enableWA.preview.template.yaml, charts/civil-ga-ccd/values.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml, charts/civil-ga-ccd/values.yaml
=> DTSCCI-613 Enable WA step 1

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14406
Dashboard Notification - GA for LiPs - Pay application fee
```
[ ] Yes
[x ] No
```
=> CIV-14406 Dashboard Notification - GA for LiPs - Pay application fee

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14421
Added new notification scripts for GA - More Info Required event
```
[ ] Yes
[x] No
```
=> CIV-14421 - Dashboard Notification - GA for LiPs - request more info

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-9450
lip urgent applications
```
[ ] Yes
[x] No
```
=> CIV-9450 added ccd events for urgent lips

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json
=> CIV-0000 Bulk cui sprint branch 

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14430
Dashboard Notification - GA for LiPs
```
[ ] Yes
[x] No
```
=> CIV-14430 Dashboard notification for GA Lip Hwf

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEventToComplexTypes/TranslatedDocument-CUI-nonprod.json, ga-ccd-definition/CaseEventToFields/UploadTranslatedDocument-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/ComplexTypes/TranslatedDocument-CUI-nonprod.json, ga-ccd-definition/FixedLists/TranslatedDocumentType-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-15110
Add UPLOAD_TRANSLATED_DOCUMENT event
```
[ ] Yes
[x] No
```
=> CIV-15110 Add UPLOAD_TRANSLATED_DOCUMENT event

README.md, bin/import-ccd-definition.sh, bin/setup-devuser-preview-env.sh, bin/variables/load-dev-user-preview-environment-variables.sh
https://tools.hmcts.net/jira/browse/DTSCCI-814
```
[ ] Yes
[ ] No
```
=> DTSCCI-814 add scripts dev env

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14423
Add event for written reps notification deletion
```
[ ] Yes
[x] No
```
=> CIV-14423 Add event for written reps notification deletion

ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-14410
https://tools.hmcts.net/jira/browse/CIV-14429
```
[ ] Yes
[ ] No
```
=> CIV-0000 Bulk sp4 to master

bin/add-roles.sh, src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/CIV-15062
Add roles
```
[ ] Yes
[x] No
```
=> CIV-15062 - add roles update

e2e/api/dataHelper.js, e2e/pages/generalApplication/hearingDetails.page.js, e2e/pages/generalApplication/responseJourneyPages/responseHearingDetails.page.js, e2e/pages/generalApplication/urgencyCheck.page.js
=> DTSCCI-973 - Removing hardcoded years from tests

e2e/fixtures/ga-ccd/createGeneralApplicationLR.js
=> CIV-00000 Master Failure Api test bug fix

e2e/tests/ui_tests/cp_tests/1v1_CP_ApplicationOrders_test.js
=> CIV-0000 UI Skip tests master fix

e2e/api/steps.js
=> CIV-00000 REVERT 2

Jenkinsfile_CNP
=> CIV-0000 fixed ccd import aat

e2e/fixtures/events/cui/hwf.js
https://tools.hmcts.net/jira/browse/CIV-15457
Update HWF js
```
[ ] Yes
[ ] No
```
=> CIV-15457 update hwf js

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-COSC-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-15654
```
[ ] Yes
[ ] No
```
=> CIV-15654 CoSc- View application

e2e/api/steps.js
=> DTSCCI-1145 - disabling CARM on LR v LR GA api tests

e2e/pages/generalApplication/judgesJourneyPages/judgesSummary.page.js, e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js, ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json, ga-ccd-definition/ComplexTypes/GAJudicialMakeAnOrderGAspec.json
https://tools.hmcts.net/jira/browse/DTSCCI-940
```
[ ] Yes
[ ] No
```
=> DTSCCI-940 hiding field as per request

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/ComplexTypes/GeneralApplicationGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-15650
Add new fields for judge orders and reasons
```
[ ] Yes
[x] No
```
=> CIV-15650 Add new fields for judge orders and reasons

ga-ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json, ga-ccd-definition/ComplexTypes/GAHearingDetailsRespGAspec.json, ga-ccd-definition/ComplexTypes/GAStatementOfTruthGAspec.json
https://tools.hmcts.net/jira/browse/CIV-15943
```
[ ] Yes
[x] No
```
=> CIV-15943 remove limitation of characters from text areas and add MAX 70 on name

ga-ccd-definition/CaseEventToFields/EndHearingScheduledProcessGaSpec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-15787
Added missing fields.
```
[ ] Yes
[x] No
```
=> CIV-15787 -  Upload translated document WA task is not autocompleting

ga-ccd-definition/ComplexTypes/GAHearingDetailsRespGAspec.json
https://tools.hmcts.net/jira/browse/CIV-16277
remove char limit
```
[ ] Yes
[ ] No
```
=> CIV-16277 remove char limit

e2e/api/steps.js
=> CIV-0000 supress the test

e2e/pages/generalApplication/caseFile.page.js, e2e/tests/ui_tests/cp_tests/1v1GeneralApplicationR2_test.js, e2e/tests/ui_tests/cp_tests/1v1GeneralApplication_test.js
=> DTSCCI-000 - adding supporting evidence verification into cfv V2

e2e/pages/generalApplication/caseFile.page.js, e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js
https://tools.hmcts.net/jira/browse/CIV-15815
```
[ ] Yes
[x] No
```
=> CIV-15815 fix issue with button

charts/civil-ga-ccd/Chart.yaml
=> DTSCCI-1364 ccd chart upgrade

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json, ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-16361
Add event for GA respondent notification when free app
```
[ ] Yes
[x] No
```
=> CIV-16361 Add event for GA respondent notification when free app

e2e/tests/api_unspec_claim_tests/api_1v2_notify_claim_details_offline_nightly_test.js, e2e/tests/api_unspec_claim_tests/api_1v2_notify_claim_offline_nightly_test.js
=> DTSCCI-1400 - skipping failing notify claim details steps

sonar-project.properties
=> DTSCCI-000 fix sonar issue

ga-ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json, ga-ccd-definition/ComplexTypes/GAHearingDetailsRespGAspec.json
https://tools.hmcts.net/jira/browse/CIV-16376
Updated email Id regex to allow + 
```
[ ] Yes
[x] No
```
=> CIV-16376 - Special characters cannot be inputted for email addresses - contact information

e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js
=> DTSCCI-1254 - Fixing mixtypeswithvary test

charts/civil-ga-ccd/values.enableWA.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml
=> DTSCCI-1105 patch camunda-bpm image

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json, ga-ccd-definition/CaseField/CaseFieldGAspec.json, ga-ccd-definition/CaseTypeTab/ServiceRequestGAspec.json
https://tools.hmcts.net/jira/browse/DTSCCI-1105
```
[ ] Yes
[ ] No
```
=> DTSCCI-1105 fix payment issue

ga-ccd-definition/AuthorisationComplexType/judgeProfileGAspec.json, ga-ccd-definition/AuthorisationComplexType/legalAdviserGAspec.json, ga-ccd-definition/AuthorisationComplexType/staff.json, ga-ccd-definition/AuthorisationComplexType/systemUpdateGAspec.json, ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json, ga-ccd-definition/ComplexTypes/GAJudgesHearingListGAspec.json
https://tools.hmcts.net/jira/browse/CIV-16579
Add days/hours/mins field for judge hearing estimate
```
[ ] Yes
[x] No
```
=> CIV-16579 Add days/hours/mins field for judge hearing estimate

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationComplexType/citizenGAspec-CUI-nonprod.json, ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-16568
changes to statement of truth
```
[ ] Yes
[x] No
```
=> CIV-16568 changes to statement of truth

ga-ccd-definition/CaseEventToComplexTypes/JudicialDecisionGAspec.json
https://tools.hmcts.net/jira/browse/CIV-16576
```
[ ] Yes
[ ] No
```
=> CIV-16576 - Optional field

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
=> DTSCCI-1105 fix sol permission

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json, ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
=> DTSCCI-1105 fix citizen permission non-prod

src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
=> DTSCCI-1721 wa system user security classification to restricted

charts/civil-ga-ccd/Chart.yaml, charts/civil-ga-ccd/values.aat.template.yaml, charts/civil-ga-ccd/values.enableWA.preview.template.yaml, charts/civil-ga-ccd/values.template.yaml
DTSCCI-1691
bump deprecated chart and remove temp image url
```
[ ] Yes
[ ] No
```
=> DTSCCI-1691 bump deprecated chart and remove temp image url

bin/add-roles.sh, e2e/tests/ui_tests/cp_tests/api_1v1_initiate_general_application_test.js, src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
DTSCCI-1074 Add  new doc removal role
DTSCCI-1074 Add  new doc removal role
=> DTSCCI-1074 Add  new doc removal role

e2e/tests/ui_tests/cp_tests/1v1GeneralApplication_test.js
=> CIV-0000 skipping test

e2e/tests/ui_tests/cp_tests/1v1GeneralApplication_test.js
=> CIV-1865 fix test

e2e/steps_file.js
…ing the test look for a non existant field
```
[ ] Yes
[ ] No
```
=> DTSCCI-1442 test fixed failing test by removing the extra parameter that was make

charts/civil-ga-ccd/Chart.yaml
=> DTSCCI-1891 upgrade wa chart

e2e/pages/caseView.page.js, e2e/pages/generalApplication/gaConfirmation.page.js, e2e/pages/generalApplication/gaPBANumber.page.js, e2e/tests/ui_tests/cp_tests/1v1GeneralApplicationR2_test.js, e2e/tests/ui_tests/cp_tests/1v1GeneralApplication_test.js
…ing on this point
```
[ ] Yes
[ ] No
```
=> DTSCCI-1865 test adding a fix for the spinner to conclude as all tests are fail

bin/add-roles.sh, src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
=> DTSCCI-192 adding missing role

e2e/api/steps.js, e2e/fixtures/events/claim/claimantResponseSpec.js, e2e/fixtures/events/claim/requestJudgementSpec.js, e2e/fixtures/events/cui/defendantResponseCui.js, e2e/tests/api_spec_claim_test/api_spec_1v1_certificate_of_satisfaction_test.js
https://tools.hmcts.net/jira/browse/CIV-11074
```
[ ] Yes
[ ] No
```
=> CIV-11074 Add API test Mark Judgment Paid in Full for JBA

e2e/pages/generalApplication/claimDocument.page.js, e2e/tests/api_unspec_claim_tests/api_1v2_judge_make_final_order_test.js
Fix two nightly tests
```
[ ] Yes
[x] No
```
=> CIV-17094 Fix nightly tests

e2e/pages/caseView.page.js, e2e/pages/generalApplication/claimDocument.page.js
=> test: adding the fix for the document count

Jenkinsfile_nightly, package.json, yarn.lock
=> DTSCCI-2194 Add Properlock File Package and Update Description for Nightly Parameter

e2e/run-full-functional-tests.sh
=> DTSCCI-2243 Add Missing Conversion For .failedTestFiles[] to Nightly

codecept.conf.js, e2e/run-functional-tests.sh, package.json
=> DTSCCI-2243 Remove Run All Tests When There Are No Failed Tests

package.json
=> DTSCCI-000 Change Report Name

.github/workflows/ado_artifacts_build.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> DTSCCI-2086 swtich from jitpack config

ga-ccd-definition/CaseEvent/Camunda/DocmosisEvents.json, ga-ccd-definition/CaseEventToFields/WorkAllocationIntegrationFields-CUI-Welsh-nonprod.json, ga-ccd-definition/FixedLists/PreTranslationGaDocumentType-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-16918
pause written representation application
```
[ ] Yes
[x] No
```
=> CIV-16914 added changes pause and delay notifications

Jenkinsfile_CNP
=> CIV-00000 run functional test

ga-ccd-definition/CaseTypeTab/Documents-CUI-Welsh-nonprod.json, ga-ccd-definition/FixedLists/PreTranslationGaDocumentType-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-17562
grant wlu access 
```
[ ] Yes
[x] No
```
=> CIV-17562 grant wlu access

ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json, ga-ccd-definition/CaseEvent/Camunda/CaseEvents.json
=> DTSCCI-2699 adding event to re-trigger WA task on GA cases

ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-Welsh-nonprod.json
https://tools.hmcts.net/jira/browse/CIV-17704
wlu admin access
```
[ ] Yes
[x] No
```
=> CIV-17704 wlu admin access
